### ISSUE TITLE
Private key shown in process list

### ISSUE THREAD

**Issue by ITNerdbox** [dallenwilson/gstm#12]
Hi,

When entering the private key in the GUI, this key is shown when executing ps. Other users on the system could easily obtain other users' private key this way.

`root@host:~# ps aux | grep ssh
user   19130  0.0  0.0  26416  6668 ?        S    18:18   0:00 ssh server_ip -p 22 -i -----BEGIN OPENSSH PRIVATE KEY----- [here's my private key] -----END OPENSSH PRIVATE KEY----- -l remote_user -nN -L10000:10.1.0.10:81 -o ConnectTimeout=5 -o NumberOfPasswordPrompts=1
`

A good work around is using the path to the private key instead. However, from a security perspective I'd recommend only to allow the path to the private key and not fill out the private key itself.

**Comment by dallenwilson** [comment]
That's a pretty serious security hole, but I can't reproduce it. The path is used, not the key itself:
`warped@mondain ~/.ssh $ ps aux | grep ssh | grep testingpi
warped   20603  0.0  0.0  11240  4504 pts/3    S+   11:04   0:00 ssh testingpi -p 22 -i /home/warped/.ssh/aws-grainmon.id_rsa -l pi -nN -o ConnectTimeout=5 -o NumberOfPasswordPrompts=1
`

The code that launches ssh is in src/fnssht.c, and is nearly untouched from the original v1.2 I based this gtk3 port on. The specific function is gstm_ssht_starttunnel(int id) and the snippet of code that appends the private key to the list of arguments is:
`if (strlen ((char *)gSTMtunnels[id]->privkey)>1) {`
`hargs->sshargs = gstm_ssht_addssharg (hargs->sshargs, "-i");`
 `hargs->sshargs = gstm_ssht_addssharg (hargs->sshargs, (char *)gSTMtunnels[id]->privkey);`
`}`

Where did you get the build you're using?

**Comment by ITNerdbox** [comment]
I've used the PPA: 

`deb http://ppa.launchpad.net/dallen.wilson/ppa/ubuntu eoan main`

I just realized that your GUI uses ssh in the background to connect to the server. Since I am using public key authentication, I can basically fill out anything in that private key input field as I am able to automatically authenticate to my server using the CLI.

I'm sorry but this is not an issue after all.

**Comment by dallenwilson** [comment]
I've never actually used the privkey input field, myself. But it was there in v1.2, so I kept it around.

This is still potentially an issue, because there's nothing in the gstm codebase that reads the contents of a private keyfile, or passes those contents to ssh. All that should be referenced is the file path. If you're seeing the actual key being used, something is wrong.

I've just confirmed that [tarball used by launchpad](https://launchpad.net/~dallen.wilson/+archive/ubuntu/ppa/+sourcefiles/gstm/1.3.6-1warped1/gstm_1.3.6.orig.tar.gz) to compile the deb package does match the [1.3.6 release tarball](https://github.com/dallenwilson/gstm/releases/download/1.3.6/gstm-1.3.6.tar.gz) available on github (sha256 checksum is 904569a898a479b71afb99a6eb4c2c722aef8f67a8ba671d0c2cfc322db3956c if you'd care to verify it). If it's not too much trouble, can you compile gstm from source on your system, using either or both tarballs, and see if you're still seeing the key when running the compiled binary?

**Comment by dallenwilson** [comment]
Just for fun, I unpacked gstm_1.3.6-1warped1_amd64.deb from the PPA on my Gentoo system and ran the binary, still only shows the path, not the actual key.

I'll fire up an Ubuntu VM tonight when I'm home and see what happens.

**Comment by ITNerdbox** [comment]
Just compiled the tarball used by launchpad and I see that the result is the same. However, the thing is that I am able to automatically login using:

`ssh user@somehost.tld`

Please note: I copied and pasted the private key content in the the GUI's field. It's basically a lack of input validation because when anything is entered there you'd expect the code to check if the file exists and has permission to read its content.

Also, how useful is this input box still, If a system is configured to automatically login using public key authentication anyway?

**Comment by dallenwilson** [comment]
You... entered the private key itself in the privkey field of the GUI, instead of the path to the file? I wish you had specified that at the beginning. I'll update the documentation to make it clear that the privkey field is intended to be used for the path to a key file, not the key itself. The field is a bit small for entering a full key.

You're right, there's no input validation of that field, or any others. gstm is just a (very) simple front-end to openssh, and openssh does it's own validation on all arguments supplied to it. Tell it to use a key file that it can't read/access/find, and it will come back with an error to let you know that, which gstm will catch and issue a pop-up for. No different than entering a username that the server doesn't recognize.

As to it's usefulness, the only scenario I can think of is if you connect to a server that's configured for both password and pubkey authentication, you connect from a machine that isn't yours or doesn't have your ~/.ssh/config set up, and/or you keep your private key on some form of removable storage (think keychain usb drive). As I said, I've never used the privkey field. It's been part of the program since at least 2006; Maybe ssh wasn't quite as automatic back then. If I ever track down the original author, I'll ask him about it.
