### ISSUE TITLE
Private Key. Can not get it work

### ISSUE THREAD

**Issue by mrspirytus** [dallenwilson/gstm#19]
Hello

Version: 1.3.6-1warped1

I just added your ppa and I am trying to set up my first connection. I already have a working entry in my ~/.ssh/config. So here is a fictional example for purpose of explanation.

```
Host ssh_server
    HostName x.x.x.x
    User my_user_name
    Port 3000
    ForwardX11 no
    IdentityFile ~/.ssh/id_ed25519_my_user_name.prv
```

When I do `$ ssh ssh_server` from a terminal it works and I connect to the remote ssh server.

Now in gSTM I create a new connection:
```
Name: MyTunnel    Host: ssh_server
Login:                      Port: 3000
                                Privkey: ???????
```
Should `Privkey` be the path to my key file? or contents?
I did try:
- Leave it empty hoping it will get it from ~/.ssh/config
- Specify path ` ~/.ssh/id_ed25519_my_user_name.prv`
- Copy entire contents of  ~/.ssh/id_ed25519_my_user_name.prv to this field.

When I try to connect I am asked about the password.

It would be good to add a visible gSTM version in the title or About window vs looking up with `apt show`. 
Add button to select private key or if left empty it should get it from ~/.ssh/config

Thank you

**Comment by dallenwilson** [comment]
PrivKey should be the path to the key file. It is passed to ssh with the '-i' flag, as per the ssh man page. The next version of gSTM will have somewhat better labelling, hopefully so that is made clearer to the user. It's not the first time PrivKey has caused confusion. A file selection button is on the wishlist, but not much of a priority.

As to your problem, leaving it empty should work fine, but with v1.3.6 you'll need to specify your username as well as the port. gSTM doesn't read, write or touch `~/.ssh/config`, but ssh is smart enough to recognize the host and figure out which keyfile to use, provided it got a proper set of launch options. Without the username, it isn't getting that.

In your example, you're launching manually with `ssh ssh_server`, but gSTM is launching with `ssh -P 3000 @ssh_server`, which are not at all the same thing. `ssh -P 3000 user@ssh_server` will work a lot better.

The next release will allow just a hostname, without port and user, which will solve this sort of keyfile problem completely. It will also include a debug mode, to see exactly what options ssh is being launched with and hopefully cut down on any problems related to this one.

The version number is already shown in the About window, directly under the Lock logo and the name. If you're not seeing it there, then something is going wrong in the debian package. Please send a screenshot of what you do see.

**Comment by mrspirytus** [comment]
I figure it out. Looks like it had problem with ~/.ssh/file.prv vs /home/mr/.ssh/file.prv
I am closing this then
