### ISSUE TITLE
when trying to ./configure ...

### ISSUE THREAD

**Issue by AJavierSanchez** [dallenwilson/gstm#29]
./configure: line 3895: syntax error near unexpected token `0.35.0'
./configure: line 3895: `IT_PROG_INTLTOOL(0.35.0)'

autogen.sh reports some errors and warnings so I have to install libglib2.0-dev in order to remove autogen errors and then modify configure.ac and Makefile.am in order to remove the warnings

these were the warnings
libtoolize: Consider adding 'AC_CONFIG_MACRO_DIRS([m4])' to configure.ac,
libtoolize: and rerunning libtoolize and aclocal.
libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.

after the modifications were made autogen.sh ends with no warnings, but the configure keeps ending with the same error.

**Comment by dallenwilson** [comment]
The libtoolize warnings can be safely ignored at this time, and there is no need to modify `configure.ac` or `Makefile.am` to deal with them.

The -dev package for glib is required to build gSTM. It's not explicitly listed because it's also required for gtk3, and gtk3's -dev package usually pulls it in.

Starting from a fresh copy of the source, with libglib2.0-dev installed and ignoring any lbtoolize warnings, are you able to run `autogen.sh` and `configure` without that error appearing?

**Comment by dallenwilson** [comment]
I pushed a new commit to master, which should deal with the libtoolize warnings. Please give it a try.

**Comment by AJavierSanchez** [comment]
Hi. Now it works!. However I have to install a few more packages in Ubuntu 20.04. 
Here they are:
    libgtk-3-dev, libxml2-dev, libappindicator3-dev and gir1.2-appindicator3-0.1. 
    
thank you very much!, great work!

**Comment by AJavierSanchez** [comment]
If you want to fix a little warning, when you run the autogen.sh, it prompts this message

aclocal: warning: couldn't open directory 'm4': No such file or directory

**Comment by dallenwilson** [comment]
libgtk3 and libxml2, along with their -dev packages, are already listed in the README as required when building from source. libappindicator will be added to the list in the next commit.

It looks like autoreconf doesn't auto-create the m4 directory, so I'll add an empty one to the repo with the next commit.

**Comment by dallenwilson** [comment]
Addressed in commit https://github.com/dallenwilson/gstm/commit/fef0aafcdc2477bada7ceae1135f69ba7bfffd85. Thanks for bringing it to my attention.
